FROM ubuntu:latest

WORKDIR /app

RUN apt update -y && apt install -y curl wget

CMD wget 'https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2022-09-26/2022-09-22-raspios-bullseye-armhf.img.xz'
